### ISSUE TITLE
grunt fails

### ISSUE THREAD

**Issue by haimivan** [bayne/github-compare#3]
Hi,

I install grunt with:
`npm install -g grunt-cli`

I execute grunt in the directory where github-compare is located with:
`$ grunt
`and get and error:

```
Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.

Aborted due to warnings.

```
environment:

```
$ npm --version
3.10.10

```
`ubuntu 14.04
`
Thanks in advance!

Details:

```
npm install -g grunt-cli
/home/this/.nvm/versions/node/v6.11.0/bin/grunt -> /home/this/.nvm/versions/node/v6.11.0/lib/node_modules/grunt-cli/bin/grunt
/home/this/.nvm/versions/node/v6.11.0/lib
└─┬ grunt-cli@1.2.0 
 ├─┬ findup-sync@0.3.0 
 │ └─┬ glob@5.0.15 
 │   ├─┬ inflight@1.0.6 
 │   │ └── wrappy@1.0.2 
 │   ├── inherits@2.0.3 
 │   ├─┬ minimatch@3.0.4 
 │   │ └─┬ brace-expansion@1.1.8 
 │   │   ├── balanced-match@1.0.0 
 │   │   └── concat-map@0.0.1 
 │   ├── once@1.4.0 
 │   └── path-is-absolute@1.0.1 
 ├── grunt-known-options@1.1.0 
 ├─┬ nopt@3.0.6 
 │ └── abbrev@1.1.1 
 └── resolve@1.1.7 

this@this-computername:~/4me/Technologie/0030-do/0060-compare-github-repos-meta$ grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
this@this-computername:~/4me/Technologie/0030-do/0060-compare-github-repos-meta$ git clone https://github.com/bayne/github-compare
Cloning into 'github-compare'...
remote: Counting objects: 1474, done.
remote: Total 1474 (delta 0), reused 0 (delta 0), pack-reused 1474
Receiving objects: 100% (1474/1474), 3.09 MiB | 809.00 KiB/s, done.
Resolving deltas: 100% (304/304), done.
Checking connectivity... done.
this@this-computername:~/4me/Technologie/0030-do/0060-compare-github-repos-meta$ cd github-compare/
this@this-computername:~/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare$ npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated grunt-bower-install@1.6.0: use grunt-wiredep instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated bower@1.3.12: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated connect@2.19.6: connect 2.x series is deprecated
npm WARN prefer global jshint@2.5.11 should be installed with -g
npm WARN prefer global bower@1.3.12 should be installed with -g
github-compare@0.0.0 /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare
├─┬ grunt@0.4.5 
│ ├── async@0.1.22 
│ ├── coffee-script@1.3.3 
│ ├── colors@0.6.2 
│ ├── dateformat@1.0.2-1.2.3 
│ ├── eventemitter2@0.4.14 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.1.3 
│ │ ├─┬ glob@3.2.11 
│ │ │ ├── inherits@2.0.3 
│ │ │ └── minimatch@0.3.0 
│ │ └── lodash@2.4.2 
│ ├── getobject@0.1.0 
│ ├─┬ glob@3.1.21 
│ │ ├── graceful-fs@1.2.3 
│ │ └── inherits@1.0.2 
│ ├─┬ grunt-legacy-log@0.1.3 
│ │ ├─┬ grunt-legacy-log-utils@0.1.1 
│ │ │ ├── lodash@2.4.2 
│ │ │ └── underscore.string@2.3.3 
│ │ ├── lodash@2.4.2 
│ │ └── underscore.string@2.3.3 
│ ├── grunt-legacy-util@0.2.0 
│ ├── hooker@0.2.3 
│ ├── iconv-lite@0.2.11 
│ ├─┬ js-yaml@2.0.5 
│ │ ├─┬ argparse@0.1.16 
│ │ │ ├── underscore@1.7.0 
│ │ │ └── underscore.string@2.4.0 
│ │ └── esprima@1.0.4 
│ ├── lodash@0.9.2 
│ ├─┬ minimatch@0.2.14 
│ │ ├── lru-cache@2.7.3 
│ │ └── sigmund@1.0.1 
│ ├─┬ nopt@1.0.10 
│ │ └── abbrev@1.1.1 
│ ├── rimraf@2.2.8 
│ ├── underscore.string@2.2.1 
│ └── which@1.0.9 
├─┬ grunt-bower-install@1.6.0 
│ ├─┬ bower-config@0.5.3 
│ │ ├── graceful-fs@2.0.3 
│ │ ├── mout@0.9.1 
│ │ ├─┬ optimist@0.6.1 
│ │ │ ├── minimist@0.0.10 
│ │ │ └── wordwrap@0.0.3 
│ │ └── osenv@0.0.3 
│ └─┬ wiredep@1.5.0 
│   ├─┬ chalk@0.1.1 
│   │ ├── ansi-styles@0.1.2 
│   │ └── has-color@0.1.7 
│   ├─┬ glob@3.2.11 
│   │ └── minimatch@0.3.0 
│   ├── lodash@1.3.1 
│   └─┬ through2@0.4.2 
│     ├─┬ readable-stream@1.0.34 
│     │ ├── core-util-is@1.0.2 
│     │ ├── isarray@0.0.1 
│     │ └── string_decoder@0.10.31 
│     └─┬ xtend@2.1.2 
│       └── object-keys@0.4.0 
├─┬ grunt-bower-task@0.4.0 
│ ├─┬ bower@1.3.12 
│ │ ├── abbrev@1.0.9 
│ │ ├── archy@0.0.2 
│ │ ├── bower-endpoint-parser@0.2.2 
│ │ ├─┬ bower-json@0.4.0 
│ │ │ ├── deep-extend@0.2.11 
│ │ │ ├── graceful-fs@2.0.3 
│ │ │ └── intersect@0.0.3 
│ │ ├── bower-logger@0.2.2 
│ │ ├─┬ bower-registry-client@0.2.4 
│ │ │ ├── async@0.2.10 
│ │ │ ├── graceful-fs@2.0.3 
│ │ │ ├── lru-cache@2.3.1 
│ │ │ ├── mkdirp@0.3.5 
│ │ │ ├─┬ request@2.51.0 
│ │ │ │ ├── caseless@0.8.0 
│ │ │ │ ├─┬ combined-stream@0.0.7 
│ │ │ │ │ └── delayed-stream@0.0.5 
│ │ │ │ ├─┬ form-data@0.2.0 
│ │ │ │ │ ├── async@0.9.2 
│ │ │ │ │ └─┬ mime-types@2.0.14 
│ │ │ │ │   └── mime-db@1.12.0 
│ │ │ │ ├── oauth-sign@0.5.0 
│ │ │ │ └── qs@2.3.3 
│ │ │ └── request-replay@0.2.0 
│ │ ├─┬ cardinal@0.4.0 
│ │ │ └── redeyed@0.4.4 
│ │ ├── chalk@0.5.0 
│ │ ├── chmodr@0.1.0 
│ │ ├─┬ decompress-zip@0.0.8 
│ │ │ ├─┬ binary@0.3.0 
│ │ │ │ ├── buffers@0.1.1 
│ │ │ │ └─┬ chainsaw@0.1.0 
│ │ │ │   └── traverse@0.3.9 
│ │ │ ├── graceful-fs@3.0.11 
│ │ │ ├── mkpath@0.1.0 
│ │ │ ├── nopt@2.2.1 
│ │ │ ├── readable-stream@1.1.14 
│ │ │ └── touch@0.0.2 
│ │ ├─┬ fstream@1.0.11 
│ │ │ └── graceful-fs@4.1.11 
│ │ ├─┬ fstream-ignore@1.0.5 
│ │ │ └─┬ minimatch@3.0.4 
│ │ │   └─┬ brace-expansion@1.1.8 
│ │ │     ├── balanced-match@1.0.0 
│ │ │     └── concat-map@0.0.1 
│ │ ├─┬ glob@4.0.6 
│ │ │ ├── minimatch@1.0.0 
│ │ │ └─┬ once@1.4.0 
│ │ │   └── wrappy@1.0.2 
│ │ ├─┬ graceful-fs@3.0.11 
│ │ │ └── natives@1.1.0 
│ │ ├─┬ handlebars@2.0.0 
│ │ │ ├── optimist@0.3.7 
│ │ │ └─┬ uglify-js@2.3.6 
│ │ │   ├── async@0.2.10 
│ │ │   ├── optimist@0.3.7 
│ │ │   └── source-map@0.1.43 
│ │ ├─┬ inquirer@0.7.1 
│ │ │ ├─┬ cli-color@0.3.3 
│ │ │ │ ├── d@0.1.1 
│ │ │ │ ├─┬ es5-ext@0.10.37 
│ │ │ │ │ ├─┬ es6-iterator@2.0.3 
│ │ │ │ │ │ └── d@1.0.0 
│ │ │ │ │ └─┬ es6-symbol@3.1.1 
│ │ │ │ │   └── d@1.0.0 
│ │ │ │ ├─┬ memoizee@0.3.10 
│ │ │ │ │ ├─┬ es6-weak-map@0.1.4 
│ │ │ │ │ │ ├── es6-iterator@0.1.3 
│ │ │ │ │ │ └── es6-symbol@2.0.1 
│ │ │ │ │ ├─┬ event-emitter@0.3.5 
│ │ │ │ │ │ └── d@1.0.0 
│ │ │ │ │ ├── lru-queue@0.1.0 
│ │ │ │ │ └── next-tick@0.2.2 
│ │ │ │ └─┬ timers-ext@0.1.2 
│ │ │ │   └── next-tick@1.0.0 
│ │ │ ├─┬ figures@1.7.0 
│ │ │ │ └── object-assign@4.1.1 
│ │ │ ├── lodash@2.4.2 
│ │ │ ├── mute-stream@0.0.4 
│ │ │ ├─┬ readline2@0.1.1 
│ │ │ │ └─┬ strip-ansi@2.0.1 
│ │ │ │   └── ansi-regex@1.1.1 
│ │ │ ├── rx@2.5.3 
│ │ │ └── through@2.3.8 
│ │ ├─┬ insight@0.4.3 
│ │ │ ├── async@0.9.2 
│ │ │ ├─┬ configstore@0.3.2 
│ │ │ │ ├── graceful-fs@3.0.11 
│ │ │ │ ├─┬ js-yaml@3.10.0 
│ │ │ │ │ ├─┬ argparse@1.0.9 
│ │ │ │ │ │ └── sprintf-js@1.0.3 
│ │ │ │ │ └── esprima@4.0.0 
│ │ │ │ ├── object-assign@2.1.1 
│ │ │ │ ├─┬ osenv@0.1.4 
│ │ │ │ │ ├── os-homedir@1.0.2 
│ │ │ │ │ └── os-tmpdir@1.0.2 
│ │ │ │ ├── user-home@1.1.1 
│ │ │ │ ├── uuid@2.0.3 
│ │ │ │ └── xdg-basedir@1.0.1 
│ │ │ ├─┬ inquirer@0.6.0 
│ │ │ │ └── lodash@2.4.2 
│ │ │ ├─┬ lodash.debounce@2.4.1 
│ │ │ │ ├── lodash.isfunction@2.4.1 
│ │ │ │ ├─┬ lodash.isobject@2.4.1 
│ │ │ │ │ └── lodash._objecttypes@2.4.1 
│ │ │ │ └─┬ lodash.now@2.4.1 
│ │ │ │   └── lodash._isnative@2.4.1 
│ │ │ ├── object-assign@1.0.0 
│ │ │ ├─┬ os-name@1.0.3 
│ │ │ │ ├─┬ osx-release@1.1.0 
│ │ │ │ │ └── minimist@1.2.0 
│ │ │ │ └─┬ win-release@1.1.1 
│ │ │ │   └── semver@5.4.1 
│ │ │ └─┬ tough-cookie@0.12.1 
│ │ │   └── punycode@1.4.1 
│ │ ├── is-root@1.0.0 
│ │ ├── junk@1.0.3 
│ │ ├── lockfile@1.0.3 
│ │ ├── lru-cache@2.5.2 
│ │ ├─┬ mkdirp@0.5.0 
│ │ │ └── minimist@0.0.8 
│ │ ├── nopt@3.0.6 
│ │ ├── opn@1.0.2 
│ │ ├── osenv@0.1.0 
│ │ ├─┬ p-throttler@0.1.0 
│ │ │ └── q@0.9.7 
│ │ ├─┬ promptly@0.2.0 
│ │ │ └── read@1.0.7 
│ │ ├── q@1.0.1 
│ │ ├─┬ request@2.42.0 
│ │ │ ├── aws-sign2@0.5.0 
│ │ │ ├─┬ bl@0.9.5 
│ │ │ │ └── readable-stream@1.0.34 
│ │ │ ├── caseless@0.6.0 
│ │ │ ├── forever-agent@0.5.2 
│ │ │ ├─┬ form-data@0.1.4 
│ │ │ │ ├── async@0.9.2 
│ │ │ │ └── mime@1.2.11 
│ │ │ ├─┬ hawk@1.1.1 
│ │ │ │ ├── boom@0.4.2 
│ │ │ │ ├── cryptiles@0.2.2 
│ │ │ │ ├── hoek@0.9.1 
│ │ │ │ └── sntp@0.2.4 
│ │ │ ├─┬ http-signature@0.10.1 
│ │ │ │ ├── asn1@0.1.11 
│ │ │ │ ├── assert-plus@0.1.5 
│ │ │ │ └── ctype@0.5.3 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├── mime-types@1.0.2 
│ │ │ ├── node-uuid@1.4.8 
│ │ │ ├── oauth-sign@0.4.0 
│ │ │ ├── qs@1.2.2 
│ │ │ ├── stringstream@0.0.5 
│ │ │ ├── tough-cookie@2.3.3 
│ │ │ └── tunnel-agent@0.4.3 
│ │ ├─┬ request-progress@0.3.0 
│ │ │ └── throttleit@0.0.2 
│ │ ├── retry@0.6.0 
│ │ ├── semver@2.3.2 
│ │ ├─┬ shell-quote@1.4.3 
│ │ │ ├── array-filter@0.0.1 
│ │ │ ├── array-map@0.0.0 
│ │ │ ├── array-reduce@0.0.0 
│ │ │ └── jsonify@0.0.0 
│ │ ├── stringify-object@1.0.1 
│ │ ├─┬ tar-fs@0.5.2 
│ │ │ ├─┬ pump@0.3.5 
│ │ │ │ ├─┬ end-of-stream@1.0.0 
│ │ │ │ │ └── once@1.3.3 
│ │ │ │ └── once@1.2.0 
│ │ │ └─┬ tar-stream@0.4.7 
│ │ │   └── xtend@4.0.1 
│ │ ├── tmp@0.0.23 
│ │ └─┬ update-notifier@0.2.0 
│ │   ├─┬ latest-version@0.2.0 
│ │   │ └─┬ package-json@0.2.0 
│ │   │   ├─┬ got@0.3.0 
│ │   │   │ └── object-assign@0.3.1 
│ │   │   └─┬ registry-url@0.1.1 
│ │   │     └─┬ npmconf@2.1.2 
│ │   │       ├─┬ config-chain@1.1.11 
│ │   │       │ └── proto-list@1.2.4 
│ │   │       ├── ini@1.3.5 
│ │   │       ├── nopt@3.0.6 
│ │   │       ├── once@1.3.3 
│ │   │       ├── osenv@0.1.4 
│ │   │       └── uid-number@0.0.5 
│ │   ├── semver-diff@0.1.0 
│ │   └─┬ string-length@0.1.2 
│ │     └─┬ strip-ansi@0.2.2 
│ │       └── ansi-regex@0.1.0 
│ ├── lodash@0.10.0 
│ ├─┬ rimraf@2.0.3 
│ │ └── graceful-fs@1.1.14 
│ └── wrench@1.4.4 
├─┬ grunt-contrib-concat@0.5.1 
│ ├─┬ chalk@0.5.1 
│ │ ├── ansi-styles@1.1.0 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@0.1.0 
│ │ │ └── ansi-regex@0.2.1 
│ │ ├── strip-ansi@0.3.0 
│ │ └── supports-color@0.2.0 
│ └─┬ source-map@0.3.0 
│   └── amdefine@1.0.1 
├─┬ grunt-contrib-connect@0.8.0 
│ ├── async@0.9.2 
│ ├─┬ connect@2.19.6 
│ │ ├── basic-auth-connect@1.0.0 
│ │ ├─┬ body-parser@1.3.1 
│ │ │ ├── qs@0.6.6 
│ │ │ └── raw-body@1.1.6 
│ │ ├── bytes@1.0.0 
│ │ ├─┬ compression@1.0.7 
│ │ │ ├─┬ accepts@1.0.3 
│ │ │ │ └── negotiator@0.4.6 
│ │ │ ├── compressible@1.1.0 
│ │ │ └── vary@0.1.0 
│ │ ├─┬ connect-timeout@1.1.0 
│ │ │ └── debug@0.8.1 
│ │ ├── cookie@0.1.2 
│ │ ├── cookie-parser@1.1.0 
│ │ ├── cookie-signature@1.0.3 
│ │ ├─┬ csurf@1.2.1 
│ │ │ └─┬ csrf-tokens@1.0.4 
│ │ │   ├── rndm@1.2.0 
│ │ │   └── scmp@0.0.3 
│ │ ├─┬ debug@1.0.2 
│ │ │ └── ms@0.6.2 
│ │ ├── errorhandler@1.0.2 
│ │ ├── escape-html@1.0.1 
│ │ ├─┬ express-session@1.2.1 
│ │ │ ├── buffer-crc32@0.2.1 
│ │ │ ├── debug@0.8.1 
│ │ │ ├── uid2@0.0.3 
│ │ │ └── utils-merge@1.0.0 
│ │ ├── fresh@0.2.2 
│ │ ├─┬ method-override@2.0.2 
│ │ │ └── methods@1.0.1 
│ │ ├── morgan@1.1.1 
│ │ ├─┬ multiparty@3.2.8 
│ │ │ └── stream-counter@0.2.0 
│ │ ├── on-headers@0.0.0 
│ │ ├── parseurl@1.0.1 
│ │ ├── pause@0.0.1 
│ │ ├── qs@0.6.6 
│ │ ├── response-time@2.0.0 
│ │ ├── serve-favicon@2.0.1 
│ │ ├─┬ serve-index@1.1.1 
│ │ │ └── batch@0.5.0 
│ │ ├─┬ serve-static@1.2.3 
│ │ │ └─┬ send@0.4.3 
│ │ │   ├── debug@1.0.2 
│ │ │   ├─┬ finished@1.2.2 
│ │ │   │ └── ee-first@1.0.3 
│ │ │   └── range-parser@1.0.3 
│ │ ├─┬ type-is@1.2.1 
│ │ │ └── mime-types@1.0.0 
│ │ └── vhost@1.0.0 
│ ├── connect-livereload@0.4.1 
│ ├── open@0.0.5 
│ └─┬ portscanner@0.2.3 
│   └── async@0.1.15 
├─┬ grunt-contrib-jshint@0.10.0 
│ └─┬ jshint@2.5.11 
│   ├─┬ cli@0.6.6 
│   │ └─┬ glob@3.2.11 
│   │   └── minimatch@0.3.0 
│   ├─┬ console-browserify@1.1.0 
│   │ └── date-now@0.1.4 
│   ├─┬ htmlparser2@3.8.3 
│   │ ├── domelementtype@1.3.0 
│   │ ├── domhandler@2.3.0 
│   │ ├─┬ domutils@1.5.1 
│   │ │ └─┬ dom-serializer@0.1.0 
│   │ │   ├── domelementtype@1.1.3 
│   │ │   └── entities@1.1.1 
│   │ └── entities@1.0.0 
│   ├── minimatch@1.0.0 
│   ├── shelljs@0.3.0 
│   ├── strip-json-comments@1.0.4 
│   └── underscore@1.6.0 
└─┬ grunt-contrib-watch@0.6.1 
 ├── async@0.2.10 
 ├─┬ gaze@0.5.2 
 │ └─┬ globule@0.1.0 
 │   └── lodash@1.0.2 
 ├── lodash@2.4.2 
 └─┬ tiny-lr-fork@0.0.5 
   ├── debug@0.7.4 
   ├── faye-websocket@0.4.4 
   ├─┬ noptify@0.0.3 
   │ └── nopt@2.0.0 
   └── qs@0.5.6 

npm WARN github-compare@0.0.0 No repository field.
this@this-computername:~/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare$ grunt
Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.

Aborted due to warnings.

```

**Comment by haimivan** [comment]
more verbose output:
```
$ grunt --stack --debug --verbose
Initializing
Command-line options: --stack, --debug=1, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-watch/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-bower-install" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-bower-install/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-bower-install/package.json...OK
Loading "bower-install.js" tasks...OK
+ bowerInstall

Registering "grunt-bower-task" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-bower-task/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-bower-task/package.json...OK
Loading "bower_task.js" tasks...OK
+ bower

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-concat/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-connect" local Npm module tasks.
Reading /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-connect/package.json...OK
Parsing /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-connect/package.json...OK
Loading "connect.js" tasks...OK
+ connect
Loading "Gruntfile.js" tasks...OK
+ default, dev

No tasks specified, running default tasks.
Running tasks: default

Running "default" task
[D] Task source: /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/Gruntfile.js

Running "jshint" task
[D] Task source: /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/tasks/jshint.js

Running "jshint:files" (jshint) task
[D] Task source: /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/tasks/jshint.js
Verifying property jshint.files exists in config...OK
Files: Gruntfile.js, app/app.js, app/compare/compare-controllers.js, app/compare/compare-directives.js, app/compare/compare.js, components/github/github-services.js -> files
Options: force=false, reporterOutput=null, globals={"jQuery":true,"console":true,"module":true,"document":true}
Warning: Path must be a string. Received null Use --force to continue.
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.exports.lint (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/tasks/lib/jshint.js:158:36)
    at Object.<anonymous> (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt-contrib-jshint/tasks/jshint.js:44:12)
    at Object.<anonymous> (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/util/task.js:300:12)
    at /home/this/4me/Technologie/0030-do/0060-compare-github-repos-meta/github-compare/node_modules/grunt/lib/util/task.js:227:11

Aborted due to warnings.

```
